// Generated by tool/brand/generate.py. Edit the generator, then regenerate.
import 'dart:ui';

abstract final class BrandPaths {
  static Path card() => Path()
    ..fillType = PathFillType.evenOdd
    ..moveTo(10, 12)
    ..lineTo(42, 12)
    ..lineTo(60, 30)
    ..lineTo(60, 46)
    ..quadraticBezierTo(60, 52, 54, 52)
    ..lineTo(10, 52)
    ..quadraticBezierTo(4, 52, 4, 46)
    ..lineTo(4, 18)
    ..quadraticBezierTo(4, 12, 10, 12)
    ..close()
    ..moveTo(18, 22)
    ..lineTo(29, 22)
    ..quadraticBezierTo(39, 22, 39, 30)
    ..quadraticBezierTo(39, 35, 34, 37)
    ..lineTo(42, 46)
    ..lineTo(33, 46)
    ..lineTo(26, 38)
    ..lineTo(25, 38)
    ..lineTo(25, 46)
    ..lineTo(18, 46)
    ..close()
    ..moveTo(25, 28)
    ..lineTo(25, 32)
    ..lineTo(29, 32)
    ..quadraticBezierTo(32, 32, 32, 30)
    ..quadraticBezierTo(32, 28, 29, 28)
    ..close();
  static Path fold() => Path()
    ..fillType = PathFillType.evenOdd
    ..moveTo(42, 12)
    ..lineTo(60, 30)
    ..lineTo(47, 30)
    ..quadraticBezierTo(42, 30, 42, 25)
    ..close();
}
