import 'dart:convert';

/// A BERT WordPiece tokenizer, ported to Dart.
///
/// This exists because Model2Vec's runtime is `tokenise → look up → average`,
/// and the lookup is only correct if the tokenisation matches the model that
/// produced the vectors. Everything here is a faithful port of HuggingFace's
/// `BertNormalizer` + `BertPreTokenizer` + `WordPiece`; the character tables it
/// depends on are generated by `tool/embeddings/export_potion.py` rather than
/// hand-written, because a wrong table is a silent quality bug rather than a
/// crash.
///
/// `test/core/embedding_test.dart` replays fixtures produced by the Python
/// reference through this class, so a divergence fails loudly.
class WordPieceTokenizer {
  WordPieceTokenizer._({
    required Map<String, int> vocab,
    required this.unkToken,
    required this.continuingSubwordPrefix,
    required this.maxInputCharsPerWord,
    required this._fold,
    required this._punctuation,
    required this._whitespace,
    required this._formatControls,
  })  : _vocab = vocab,
        _unkId = vocab[unkToken] ?? 0;

  /// Builds from the assets emitted by the export script.
  ///
  /// [vocabText] is newline-separated with the token id being the line index.
  /// [normalizerJson] carries the generated character tables.
  factory WordPieceTokenizer.fromAssets({
    required String vocabText,
    required String normalizerJson,
  }) {
    final List<String> lines = const LineSplitter().convert(vocabText);
    final Map<String, int> vocab = <String, int>{
      for (int i = 0; i < lines.length; i++) lines[i]: i,
    };

    final Map<String, dynamic> cfg =
        jsonDecode(normalizerJson) as Map<String, dynamic>;

    final Map<String, dynamic> rawFold =
        cfg['fold'] as Map<String, dynamic>? ?? const <String, dynamic>{};

    return WordPieceTokenizer._(
      vocab: vocab,
      fold: <int, String>{
        for (final MapEntry<String, dynamic> e in rawFold.entries)
          int.parse(e.key): e.value as String,
      },
      punctuation: _intSet(cfg['punctuation']),
      whitespace: _intSet(cfg['whitespace']),
      formatControls: _intSet(cfg['formatControls']),
      unkToken: cfg['unkToken'] as String? ?? '[UNK]',
      continuingSubwordPrefix: cfg['continuingSubwordPrefix'] as String? ?? '##',
      maxInputCharsPerWord: cfg['maxInputCharsPerWord'] as int? ?? 100,
    );
  }

  static Set<int> _intSet(Object? raw) => <int>{
        for (final Object? v in (raw as List<dynamic>? ?? const <dynamic>[]))
          v! as int,
      };

  final Map<String, int> _vocab;

  /// Codepoint → replacement, combining accent-stripping and lowercasing into
  /// one lookup. Precomputed because Dart has no Unicode NFD in core.
  final Map<int, String> _fold;

  final Set<int> _punctuation;
  final Set<int> _whitespace;
  final Set<int> _formatControls;
  final int _unkId;

  final String unkToken;
  final String continuingSubwordPrefix;
  final int maxInputCharsPerWord;

  int get vocabSize => _vocab.length;

  /// Token ids for [text], with no special tokens.
  ///
  /// Model2Vec encodes with `add_special_tokens=False`, so no `[CLS]`/`[SEP]`.
  List<int> encode(String text) {
    final List<int> ids = <int>[];
    for (final String token in tokenize(text)) {
      ids.add(_vocab[token] ?? _unkId);
    }
    return ids;
  }

  /// The token strings, exposed so tests can compare against the reference
  /// tokenisation rather than only the final vector.
  List<String> tokenize(String text) {
    final List<String> out = <String>[];
    for (final String word in _preTokenize(_normalize(text))) {
      out.addAll(_wordPiece(word));
    }
    return out;
  }

  // --- BertNormalizer ------------------------------------------------------

  /// clean_text → handle_chinese_chars → strip_accents → lowercase.
  ///
  /// The last two are folded into a single table lookup; see [_fold].
  String _normalize(String text) {
    final StringBuffer out = StringBuffer();

    for (final int cp in text.runes) {
      // clean_text: drop nulls, replacement chars and control characters.
      if (cp == 0 || cp == 0xFFFD || _isControl(cp)) continue;

      if (_whitespace.contains(cp)) {
        out.write(' ');
        continue;
      }

      // handle_chinese_chars: isolate CJK so each character becomes its own
      // token. Irrelevant for Latin cards, but the reference does it and
      // divergence here would be invisible until it mattered.
      if (_isCjk(cp)) {
        out
          ..write(' ')
          ..writeCharCode(cp)
          ..write(' ');
        continue;
      }

      final String? folded = _fold[cp];
      if (folded != null) {
        out.write(folded);
      } else {
        out.writeCharCode(cp);
      }
    }
    return out.toString();
  }

  /// Category `Cc`, `Cf`, `Cs` or `Co`.
  ///
  /// Tab, newline and carriage return are deliberately excluded: BERT counts
  /// them as whitespace, not control.
  bool _isControl(int cp) {
    if (cp == 0x09 || cp == 0x0A || cp == 0x0D) return false;
    if (cp < 0x20 || (cp >= 0x7F && cp <= 0x9F)) return true; // Cc
    if (cp >= 0xD800 && cp <= 0xDFFF) return true; // Cs, surrogates
    if (cp >= 0xE000 && cp <= 0xF8FF) return true; // Co, private use
    if (cp >= 0xF0000) return true; // Co, supplementary private use
    return _formatControls.contains(cp); // Cf
  }

  static bool _isCjk(int cp) =>
      (cp >= 0x4E00 && cp <= 0x9FFF) ||
      (cp >= 0x3400 && cp <= 0x4DBF) ||
      (cp >= 0x20000 && cp <= 0x2A6DF) ||
      (cp >= 0x2A700 && cp <= 0x2B73F) ||
      (cp >= 0x2B740 && cp <= 0x2B81F) ||
      (cp >= 0x2B820 && cp <= 0x2CEAF) ||
      (cp >= 0xF900 && cp <= 0xFAFF) ||
      (cp >= 0x2F800 && cp <= 0x2FA1F);

  // --- BertPreTokenizer ----------------------------------------------------

  /// Splits on whitespace, then breaks each punctuation mark into its own word.
  ///
  /// This is why `t-shirt` becomes `t`, `-`, `shirt` rather than one unknown
  /// token, and why `info@medica.com` splits around the `@` and the dots.
  List<String> _preTokenize(String text) {
    final List<String> words = <String>[];
    final StringBuffer current = StringBuffer();

    void flush() {
      if (current.isNotEmpty) {
        words.add(current.toString());
        current.clear();
      }
    }

    for (final int cp in text.runes) {
      if (cp == 0x20) {
        flush();
      } else if (_punctuation.contains(cp)) {
        flush();
        words.add(String.fromCharCode(cp));
      } else {
        current.writeCharCode(cp);
      }
    }
    flush();
    return words;
  }

  // --- WordPiece -----------------------------------------------------------

  /// Greedy longest-match-first over the vocabulary.
  ///
  /// A word that cannot be fully covered yields a single `[UNK]` — partial
  /// coverage is discarded, which matches the reference and matters because
  /// half-tokenised words would otherwise pollute the average.
  List<String> _wordPiece(String word) {
    if (word.isEmpty) return const <String>[];

    final List<int> chars = word.runes.toList();
    if (chars.length > maxInputCharsPerWord) return <String>[unkToken];

    final List<String> pieces = <String>[];
    int start = 0;

    while (start < chars.length) {
      int end = chars.length;
      String? match;

      while (start < end) {
        final String candidate = start == 0
            ? String.fromCharCodes(chars.sublist(start, end))
            : '$continuingSubwordPrefix'
                '${String.fromCharCodes(chars.sublist(start, end))}';

        if (_vocab.containsKey(candidate)) {
          match = candidate;
          break;
        }
        end--;
      }

      if (match == null) return <String>[unkToken];

      pieces.add(match);
      start = end;
    }
    return pieces;
  }
}
